### ISSUE TITLE
Lensy API

### ISSUE THREAD

**Issue by paf31** [VesaKarvonen/purescript-fix#1]
Adding `Semigroupoid`, `Profunctor`, `Strong`, and `Choice` instances for `Proxy` and `FixEff Proxy` would allow us to use `purescript-profunctor-lenses` to compose proxies using isos, lenses and prisms. This essentially generalizes your instances for isos and tuples.

To be clear, this would (I think) allow writing things like 

``` purescript
tupleProxy p1 p2 = _1 p1 >>> _2 p2
```

for `Tuple`, and isos could just be applied directly to proxies. Also, since `Proxy a a -> FixEff a` is _also_ a `Profunctor`/`Choice` etc., we could build `MonadFix` instances this way too.

I've started working through the details, but wanted to check if you'd take a PR first? I appreciate it might be a bit of a diversion from the goal of the library.

Thanks for this great library!

**Comment by polytypic** [comment]
Thanks, what you suggest sounds like a good idea.  I'm not opposed to taking pull requests, however...

My goal for the library was actually just to show that it is indeed possible to have `MonadFix` in a strict language to help a colleague (@anttih) who is interested in the possibility of writing a PS library using it.  The technique can probably be improved in many ways.

For a type class to be really useful it needs to be defined before (or with) any types for which there are instances of it.  At the moment `purescript-fix` depends on `purescript-lazy` and `purescript-lists`, but this is, IMO, not really a good thing, because `purescript-fix` doesn't really depend on either&mdash;they are merely used as examples.  So, assuming that having `Fix` and `MonadFix` is of value, I think the dependencies should be the other way.

I don't really have any claims to the code or need to hold copyright to it.  So, if there is desire to move the idea under `purescript` group or even into the prelude to make it convenient to add syntactic support for recursive do, then feel free to do so.
